name: NickUI
main: NoobMCBG\NickUI\Main
api: 3.0.0
version: 1.0.0
author: NoobMCBG

commands:
  nick:
    description: Mở Menu Nick
    usage: /nick

permissions:
  nick.command:
    description: Quyền Nick
    default: op